<?php
/**
 * @file
 * This file serves as a stub file for the many example modules in the
 * @link http://backdropcms.org/project/examples Examples for Developers @endlink
 * project.
 *
 * One might say this module is an example of documentation. However, note that
 * the example submodules define many Doxygen groups, which may or may not be a
 * good strategy for other modules.
 */

/**
 * @defgroup examples Examples
 * @{
 * These modules are well-documented API examples for a broad range of Backdrop
 * core functionality.
 *
 * Developers can quickly learn how to use a particular API by experimenting
 * with the examples, and adapt them for their own use.
 *
 * This project is based on the
 * @link http://www.drupal.org/project/examples Examples for Developers @endlink
 * project for Drupal.
 *
 */


/**
 * @} End of 'defgroup examples'.
 */
